site_name: LASER landing page # update to your project name
site_url: https://laser.idmod.org # update to your project URL for the correct modeling framework
repo_name: laser-base.github.io # update to your repo name
repo_url: https://github.com/laser-base/laser-base.github.io # update to your repo URL
theme:
  name: material
  custom_dir: docs/customization/overrides
  font: 
    text: Roboto
    code: Roboto Mono
  logo: images/idm-logo-transparent.png
  favicon: images/favicon.ico
  features:
    - navigation.footer # include a footer with links to privacy, terms, etc.
    - content.code.copy # enable copy buttons for code blocks
    - navigation.indexes # enable parent index page for sections
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: white
      accent: light blue
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: light blue

nav: # Navigation structure for the documentation
  - Home: index.md 

# icons, semantic markup, emojis 
markdown_extensions:
  - toc:
      toc_depth: 3
  - attr_list # enables HTMl and CSS classes to inline elements
  - md_in_html # enables grids
  - admonition # warnings, etc.
  - def_list
  - pymdownx.emoji: # emojis and icons
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex: # Latex processing for math equations
      generic: true
  - pymdownx.snippets: # insert content from other files
      auto_append:
        - docs/includes/glossary.md # definitions for glossary entries
  - abbr # term/abbreviation hover descriptions
  - pymdownx.blocks.details: # allows nesting of collapsible code
  - pymdownx.highlight: # syntax highlighting for code blocks
      linenums: true
      default_lang: 'python'
  - pymdownx.inlinehilite # syntax highlighting for inline code
  - pymdownx.superfences # enables code, diagram fences to be nested in lists, etc.e
  - pymdownx.details # collapsible elements
  - pymdownx.tabbed: # tabbed content that can be toggled
      alternate_style: true
  - pymdownx.blocks.caption # captions for images, tables, etc.

# javascript and CSS customization
extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra_css: 
  - customization/css/extra.css # custom CSS for footer spacing

plugins:
  - search # search functionality
  - autorefs # automatically create linkable references
  - include-markdown # include other files, such as READMEs
  - table-reader # enables rendering of CSV/TSV files as tables


copyright: Copyright &copy; 2025 Gates Foundation. All rights reserved.

extra:
  generator: false
  footer_links:
    - text: "Privacy and Cookies Notice"
      href: "https://www.gatesfoundation.org/Privacy-and-Cookies-Notice"
    - text: "Terms of Use"
      href: "https://www.gatesfoundation.org/Terms-of-Use"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/laser-base # update to your repo
    - icon: fontawesome/regular/envelope
      link: mailto:idm@gatesfoundation.org
    - icon: octicons/globe-24
      link: https://idmod.org
    - icon: simple/youtube
      link: http://www.youtube.com/@institutefordiseasemodelin1987
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/institute-disease-modeling

  analytics:
    provider: custom
    tracking_id: GTM-NK4K647
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback! If you like, provide additional information by
            using our <a href="https://app.smartsheet.com/b/form/ec8dbb77809949ecab7286a5ca74a206" target="_blank" rel="noopener">feedback form</a>.
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://app.smartsheet.com/b/form/ec8dbb77809949ecab7286a5ca74a206" target="_blank" rel="noopener">feedback form</a>.